//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapMyElevation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapMyElevation.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPage {
            get {
                return ResourceManager.GetString("AboutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP MY ELEVATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app requires your location settings to be turned on. Would you like to go to your Location settings now?.
        /// </summary>
        public static string AppRequiresLocation {
            get {
                return ResourceManager.GetString("AppRequiresLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Elevation.
        /// </summary>
        public static string AverageElevation {
            get {
                return ResourceManager.GetString("AverageElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Elevation: .
        /// </summary>
        public static string CurrentElevationColon {
            get {
                return ResourceManager.GetString("CurrentElevationColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Position.
        /// </summary>
        public static string CurrentPosition {
            get {
                return ResourceManager.GetString("CurrentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Display Unit.
        /// </summary>
        public static string DistanceDisplayUnit {
            get {
                return ResourceManager.GetString("DistanceDisplayUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation.
        /// </summary>
        public static string Elevation {
            get {
                return ResourceManager.GetString("Elevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation Display Unit.
        /// </summary>
        public static string ElevationDisplayUnit {
            get {
                return ResourceManager.GetString("ElevationDisplayUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elevation chart.
        /// </summary>
        public static string ElevationPivot {
            get {
                return ResourceManager.GetString("ElevationPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred the last time you ran this application. Would you like to send an email to report it?.
        /// </summary>
        public static string ErrorLastTimeMessage {
            get {
                return ResourceManager.GetString("ErrorLastTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Report.
        /// </summary>
        public static string ErrorReport {
            get {
                return ResourceManager.GetString("ErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Position....
        /// </summary>
        public static string FoundPosition {
            get {
                return ResourceManager.GetString("FoundPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Current Elevation.
        /// </summary>
        public static string GetCurrentElevation {
            get {
                return ResourceManager.GetString("GetCurrentElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Elevation.
        /// </summary>
        public static string HighestElevation {
            get {
                return ResourceManager.GetString("HighestElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        public static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers.
        /// </summary>
        public static string Kilometers {
            get {
                return ResourceManager.GetString("Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string KilometersAbbreviation {
            get {
                return ResourceManager.GetString("KilometersAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string KM {
            get {
                return ResourceManager.GetString("KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location data is not available.
        /// </summary>
        public static string LocationNotAvailable {
            get {
                return ResourceManager.GetString("LocationNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Required.
        /// </summary>
        public static string LocationRequired {
            get {
                return ResourceManager.GetString("LocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking up current position....
        /// </summary>
        public static string LookingUpCurrentPosition {
            get {
                return ResourceManager.GetString("LookingUpCurrentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest Elevation.
        /// </summary>
        public static string LowestElevation {
            get {
                return ResourceManager.GetString("LowestElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu.
        /// </summary>
        public static string MenuPage {
            get {
                return ResourceManager.GetString("MenuPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        public static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        public static string Miles {
            get {
                return ResourceManager.GetString("Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to options.
        /// </summary>
        public static string OptionsLowercase {
            get {
                return ResourceManager.GetString("OptionsLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you enjoy using Map My Elevation? Please give us 5 stars in the Windows Phone App store!.
        /// </summary>
        public static string PleaseRate {
            get {
                return ResourceManager.GetString("PleaseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions or Comments?.
        /// </summary>
        public static string QuestionsOrComments {
            get {
                return ResourceManager.GetString("QuestionsOrComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quick check.
        /// </summary>
        public static string QuickCheckPage {
            get {
                return ResourceManager.GetString("QuickCheckPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate App.
        /// </summary>
        public static string RateApp {
            get {
                return ResourceManager.GetString("RateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resuming....
        /// </summary>
        public static string Resuming {
            get {
                return ResourceManager.GetString("Resuming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Elevation Information....
        /// </summary>
        public static string RetrievingElevation {
            get {
                return ResourceManager.GetString("RetrievingElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Feedback.
        /// </summary>
        public static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Navigation....
        /// </summary>
        public static string StartingNavigation {
            get {
                return ResourceManager.GetString("StartingNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Navigation.
        /// </summary>
        public static string StartNavigation {
            get {
                return ResourceManager.GetString("StartNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Navigation.
        /// </summary>
        public static string StopNavigation {
            get {
                return ResourceManager.GetString("StopNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quick stats.
        /// </summary>
        public static string SummaryPivot {
            get {
                return ResourceManager.GetString("SummaryPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Distance.
        /// </summary>
        public static string TotalDistance {
            get {
                return ResourceManager.GetString("TotalDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time.
        /// </summary>
        public static string TotalTime {
            get {
                return ResourceManager.GetString("TotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Summary.
        /// </summary>
        public static string ViewSummary {
            get {
                return ResourceManager.GetString("ViewSummary", resourceCulture);
            }
        }
    }
}
