//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemorySquared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MemorySquared.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutLower {
            get {
                return ResourceManager.GetString("AboutLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add name.
        /// </summary>
        public static string AddName {
            get {
                return ResourceManager.GetString("AddName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Leaderboard.
        /// </summary>
        public static string AddToLeaderboard {
            get {
                return ResourceManager.GetString("AddToLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEMORY SQUARED.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose mode.
        /// </summary>
        public static string ChooseMode {
            get {
                return ResourceManager.GetString("ChooseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current: .
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable this popup in the Options menu.
        /// </summary>
        public static string DisablePopup {
            get {
                return ResourceManager.GetString("DisablePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        public static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easy.
        /// </summary>
        public static string EasyLower {
            get {
                return ResourceManager.GetString("EasyLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred the last time you ran this application. Would you like to send an email to report it?.
        /// </summary>
        public static string ErrorLastTimeMessage {
            get {
                return ResourceManager.GetString("ErrorLastTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Processing Request.
        /// </summary>
        public static string ErrorProcessingRequest {
            get {
                return ResourceManager.GetString("ErrorProcessingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Report.
        /// </summary>
        public static string ErrorReport {
            get {
                return ResourceManager.GetString("ErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error processing this request. Would you like to send the details to the developer to help get this fixed as soon as possible?.
        /// </summary>
        public static string ErrorRequestMessage {
            get {
                return ResourceManager.GetString("ErrorRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Rectangle Color.
        /// </summary>
        public static string GameRectangleColor {
            get {
                return ResourceManager.GetString("GameRectangleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Luck!.
        /// </summary>
        public static string GoodLuck {
            get {
                return ResourceManager.GetString("GoodLuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        public static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hard.
        /// </summary>
        public static string HardLower {
            get {
                return ResourceManager.GetString("HardLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Score (Easy).
        /// </summary>
        public static string HighScoreEasy {
            get {
                return ResourceManager.GetString("HighScoreEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Score (Hard).
        /// </summary>
        public static string HighScoreHard {
            get {
                return ResourceManager.GetString("HighScoreHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Memory Squared is a game that will test your memory! The object of the game is to match the pattern you see. When the game begins, you&apos;ll see a countdown from 3. After that, one rectangle will light up. Then it&apos;s your turn to match the pattern. When you tap the rectangle that lit up, you&apos;ll see the same rectangle light up again followed by one random rectangle - then it&apos;s your turn again, and so on. Match as many as you can, and add your scores to the leaderboard! See who can get the highest score betwee [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InstructionsMessage {
            get {
                return ResourceManager.GetString("InstructionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instructions.
        /// </summary>
        public static string InstructionsTitle {
            get {
                return ResourceManager.GetString("InstructionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English, United States.
        /// </summary>
        public static string LangRegionNameEnUs {
            get {
                return ResourceManager.GetString("LangRegionNameEnUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish, Spain.
        /// </summary>
        public static string LangRegionNameEsES {
            get {
                return ResourceManager.GetString("LangRegionNameEsES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main menu.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        public static string MainMenuButton {
            get {
                return ResourceManager.GetString("MainMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW HIGH SCORE!.
        /// </summary>
        public static string NewHighScore {
            get {
                return ResourceManager.GetString("NewHighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oops....
        /// </summary>
        public static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to options.
        /// </summary>
        public static string OptionsLower {
            get {
                return ResourceManager.GetString("OptionsLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paused.
        /// </summary>
        public static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you enjoy Memory Squared? Please give us 5 stars in the Windows Phone App store!.
        /// </summary>
        public static string PleaseRate {
            get {
                return ResourceManager.GetString("PleaseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous High Score.
        /// </summary>
        public static string PreviousHighScore {
            get {
                return ResourceManager.GetString("PreviousHighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Successful!.
        /// </summary>
        public static string PurchaseSuccessful {
            get {
                return ResourceManager.GetString("PurchaseSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions or Comments?.
        /// </summary>
        public static string QuestionsOrComments {
            get {
                return ResourceManager.GetString("QuestionsOrComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate App.
        /// </summary>
        public static string RateApp {
            get {
                return ResourceManager.GetString("RateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Ads.
        /// </summary>
        public static string RemoveAds {
            get {
                return ResourceManager.GetString("RemoveAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Game.
        /// </summary>
        public static string ResumeGame {
            get {
                return ResourceManager.GetString("ResumeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to Leaderboard.
        /// </summary>
        public static string SaveToLeaderboard {
            get {
                return ResourceManager.GetString("SaveToLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Feedback.
        /// </summary>
        public static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt on sequence start.
        /// </summary>
        public static string SequenceStartPrompt {
            get {
                return ResourceManager.GetString("SequenceStartPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        public static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap this box to resume.
        /// </summary>
        public static string TapToResume {
            get {
                return ResourceManager.GetString("TapToResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upon resuming, we&apos;ll show you the last complete sequence that was entered. Then you can start by matching that sequence..
        /// </summary>
        public static string UponResuming {
            get {
                return ResourceManager.GetString("UponResuming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use light theme.
        /// </summary>
        public static string UseLightTheme {
            get {
                return ResourceManager.GetString("UseLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Rectangle Color.
        /// </summary>
        public static string UserRectangleColor {
            get {
                return ResourceManager.GetString("UserRectangleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Leaderboard.
        /// </summary>
        public static string ViewLeaderboard {
            get {
                return ResourceManager.GetString("ViewLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You tapped the wrong rectangle.
        /// </summary>
        public static string WrongRectangle {
            get {
                return ResourceManager.GetString("WrongRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Score.
        /// </summary>
        public static string YourScore {
            get {
                return ResourceManager.GetString("YourScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your turn!.
        /// </summary>
        public static string YourTurn {
            get {
                return ResourceManager.GetString("YourTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s your turn to match the sequence. Tap the rectangle you just saw. Once you do, you&apos;ll see the same sequence displayed again with one additional rectangle added to the sequence..
        /// </summary>
        public static string YourTurnMessage {
            get {
                return ResourceManager.GetString("YourTurnMessage", resourceCulture);
            }
        }
    }
}
